### ISSUE TITLE
суета2

### ISSUE THREAD

**Issue by maksgir** [keksmd/ClientPart_Lab6#5]
у тебя у Мессаж определен туСтринг в нем же реализация, ты его наследуешь и переопределяешь в наследнике точно так же. Джошуа Блох вахуе 
https://github.com/keksmd/ClientPart_Lab6/blob/1d1575d2aa5380aaa2595055e9d7bdcd1af0f308/src/main/java/main/Request.java#L12

**Comment by keksmd** [comment]
Грязный код,хули
done
