### ISSUE TITLE
??????

### ISSUE THREAD

**Issue by maksgir** [keksmd/ClientPart_Lab6#7]
https://github.com/keksmd/ClientPart_Lab6/blob/1d1575d2aa5380aaa2595055e9d7bdcd1af0f308/src/main/java/main/Main.java#L93

**Comment by keksmd** [comment]
![изображение](https://github.com/keksmd/ClientPart_Lab6/assets/64474021/8dc05b3e-bd55-4999-a25f-1a5d2651deef)
лан,переименую
